#! /bin/sh

which -s hugo >>/dev/null || exit 1

git submodule update --init

commit_id=$(git rev-parse --short HEAD)
git_c1="$(git config user.name)"
git_c2="$(git config user.email)"
git_c3="$(git config core.sshCommand)"

[ -L public ] && {
	publish_dir=$(readlink public)
	rm -rf $publish_dir
	rm -f public
}

publish_dir=$(mktemp -d)
ln -s $publish_dir public
hugo --minify

cd public
git init -q
[ -n "$git_c1" ] && git config user.name  "$git_c1"
[ -n "$git_c2" ] && git config user.email "$git_c2"
[ -n "$git_c3" ] && git config core.sshCommand "$git_c3"
git remote add origin git@github.com:btogxx/btogxx.github.io.git
git branch -m publish
git add .
git commit -m "generate from $commit_id"
git push -f origin publish
cd -
rm -rf $publish_dir
rm -f public
